INSERT INTO Policies (PolicyType, Name, Description, PrereqCivic, GovernmentSlotType)
VALUES
	('POLICY_BLANK_WONDER_10_X_0', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_MILITARY' ),
    ('POLICY_BLANK_WONDER_10_X_1', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_MILITARY' ),
    ('POLICY_BLANK_WONDER_10_X_2', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_MILITARY' ),
    ('POLICY_BLANK_WONDER_10_X_10', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_DIPLOMATIC' ),
    ('POLICY_BLANK_WONDER_10_X_11', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_DIPLOMATIC' ),
    ('POLICY_BLANK_WONDER_10_X_12', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_DIPLOMATIC' ),
    ('POLICY_BLANK_WONDER_10_X_20', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_ECONOMIC' ),
    ('POLICY_BLANK_WONDER_10_X_21', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_ECONOMIC' ),
    ('POLICY_BLANK_WONDER_10_X_22', 'LOC_POLICY_BLANK_WONDER_10_X_NAME', 'LOC_POLICY_BLANK_WONDER_10_X_DESCRIPTION', 'CIVIC_CODE_OF_LAWS', 'SLOT_ECONOMIC' ),

    
INSERT INTO Types (Type, Kind)
VALUES
    ('POLICY_BLANK_WONDER_10_X_0', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_1', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_2', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_3', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_10', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_11', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_12', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_13', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_20', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_21', 'KIND_POLICY'),
    ('POLICY_BLANK_WONDER_10_X_22', 'KIND_POLICY'),